spring:
  freemarker:
    cache: false
    settings:
      auto_import: /spring.ftl as spring
  datasource:
    url: jdbc:mysql://localhost/pybbs-springboot?useSSL=false&characterEncoding=utf8
    username: zhuohao
    password: 100200
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  mvc:
    static-path-pattern: /static/**
  messages:
    basename: i18n/messages